### ISSUE TITLE
Matching statusline colors

### ISSUE THREAD

**Issue by tipu** [lifepillar/vim-wwdc16-theme#2]
Hello,

I noticed in your screen shot that the status line for vim matches the colorscheme. What needs to be done to have them match?

**Comment by lifepillar** [comment]
WWDC16 defines a one-color (forest green) status line. In the screenshot I use a custom status line with two colors. That can be obtained with a suitable definition of `statusline`, e.g.:

```
setl stl=%#NormalMode#\ %{mode(1)}\ %*\ %t
```
See `:help stl` for the details.

`NormalMode` is one of WWDC16 custom highlight groups: `NormalMode`, `InsertMode`, `ReplaceMode`, `VisualMode` and `CommandMode`, which I use in my status line, whose color changes according to the current mode. If you are interested, the full code (somewhat intricate, but mostly self-contained) is in the “Status line” section of [my vimrc](https://github.com/lifepillar/vimrc).

**Comment by tipu** [comment]
Thanks for the help.
