### ISSUE TITLE
It doesn't work in MacVim

### ISSUE THREAD

**Issue by omaks** [lifepillar/vim-wwdc16-theme#3]

**Comment by lifepillar** [comment]
It does.

**Comment by omaks** [comment]
For me it works in Terminal but when I launch MacVim it doesn't.
I tried to set "let macvim_skip_colorscheme = 1" in .vimrc but it didn't fix the problem. Also, I tried to create .gvimrc but it works in the same way. 

Could you give me instructions?

**Comment by lifepillar** [comment]
I assume that “it doesn't work” means “it is not loaded”. If it works in Terminal, it should work in MacVim too, unless MacVim uses a different configuration. Try creating a minimal `vimrc` with the following content:

```vim
set nocompatible
syntax on
colorscheme wwdc16
```

and launch MacVim from the command line as follows:

```sh
mvim -u test-vimrc
```

or

```sh
/Applications/MacVim.app/Contents/bin/mvim -u test-vimrc
```

if the first command is not found. Is the colorscheme loaded?

If not, check the values of `runtimepath` and `packpath`:

```vim
:set packpath
:set runtimepath
```

Does your `.vim` folder appear in those paths? Is WWDC16's folder inside `~/.vim/pack/*/opt` or elsewhere?

**Comment by omaks** [comment]
Thank you! Now it works. It was my mistake.
