### ISSUE TITLE
doc/tags show up in git status

### ISSUE THREAD

**Issue by totpet** [lifepillar/vim-wwdc16-theme#4]
Hi!

The `doc/tags` file is not in .gitignore, but also not in sync with the documentation, so every time I run `:Helptags`, it is changed and shows up in git status output (plugins are submodules of my .vim repository):

```diff
diff --git a/doc/tags b/doc/tags
index a25adc7..734afc0 100644
--- a/doc/tags
+++ b/doc/tags
@@ -1,3 +1,4 @@
+g:wwdc16_enable_syntax_hi_groups     wwdc16.txt      /*g:wwdc16_enable_syntax_hi_groups*
 g:wwdc16_term_italics  wwdc16.txt      /*g:wwdc16_term_italics*
 g:wwdc16_transp_bg     wwdc16.txt      /*g:wwdc16_transp_bg*
 g:wwdc16_use16 wwdc16.txt      /*g:wwdc16_use16*
```

Can you please add it to a `.gitignore` file or update it after every doc change?

**Comment by lifepillar** [comment]
Thanks for pointing that out!
