### ISSUE TITLE
The paired double quote for shell script with different color

### ISSUE THREAD

**Issue by objczl** [lifepillar/vim-wwdc16-theme#5]
<img width="647" alt="Screen Shot 2020-08-16 at 6 49 03 PM@2x" src="https://user-images.githubusercontent.com/4112633/90332658-4a025280-dff1-11ea-9a09-296944931b03.png">

**Comment by lifepillar** [comment]
That's an issue with the syntax coloring of the `sh` filetype, independent of the color scheme (try `:colo default` and the issue will still be there).

While the left double quote is assigned (correctly) syntax group `shQuote`, the right double quote has syntax group `shSpecial`. The former is highlighted as the `Operator` highlight group; the latter is highlighted as the `Special` highlight group.

So, a workaround consists in overriding the definition of one of those groups. E.g., putting this in your `vimrc` should fix it:

```
hi! link shSpecial shQuote
```

**Comment by objczl** [comment]
Thanks
